name: Primeiro workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    env:
      NOME_IMAGEM: anpapicontagem
      NOME_COMPLETO_IMAGEM: ${{ secrets.DOCKER_USERNAME }}/$NOME_IMAGEM

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login no Docker Hub
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build e Push no Docker Hub
      run: |
        cd ./APIContagem
        docker build . --file Dockerfile --tag ${{ env.NOME_COMPLETO_IMAGEM }}:latest
        docker tag ${{ env.NOME_COMPLETO_IMAGEM }}:latest ${{ env.NOME_COMPLETO_IMAGEM }}:$GITHUB_RUN_NUMBER
        docker push ${{ env.NOME_COMPLETO_IMAGEM }}
